"""empty message

Revision ID: 1716235e83f7
Revises: 2c03b24f16cb
Create Date: 2016-12-07 10:23:24.487435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1716235e83f7'
down_revision = '2c03b24f16cb'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'default')
    ### end Alembic commands ###
