"""empty message

Revision ID: 330c5d3bef40
Revises: 4b123e034e6b
Create Date: 2016-12-07 15:06:54.452349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330c5d3bef40'
down_revision = '4b123e034e6b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mblog', 'user', ['author_id'], ['id'])
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'location')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_constraint(None, 'mblog', type_='foreignkey')
    ### end Alembic commands ###
