"""empty message

Revision ID: bcbe95a7c8c1
Revises: da9a52e6dbcf
Create Date: 2016-12-07 17:37:42.386862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbe95a7c8c1'
down_revision = 'da9a52e6dbcf'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mblog', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'mblog', type_='foreignkey')
    ### end Alembic commands ###
