"""empty message

Revision ID: da9a52e6dbcf
Revises: f15454cf6a99
Create Date: 2016-12-07 17:25:12.944996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9a52e6dbcf'
down_revision = 'f15454cf6a99'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mblog', 'user', ['author_id'], ['id'])
    op.add_column('user', sa.Column('headsculpture', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'headsculpture')
    op.drop_constraint(None, 'mblog', type_='foreignkey')
    ### end Alembic commands ###
