"""empty message

Revision ID: f15454cf6a99
Revises: e1b44f7afd4c
Create Date: 2016-12-07 15:17:09.096505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15454cf6a99'
down_revision = 'e1b44f7afd4c'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'mblog', 'user', ['author_id'], ['id'])
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'name')
    op.drop_constraint(None, 'mblog', type_='foreignkey')
    ### end Alembic commands ###
